# Generated by Django 4.0.1 on 2022-02-08 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primerComponente', '0002_segundomodelo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RrimerModelo',
            new_name='PrimerModelo',
        ),
    ]
